class_name PersonConstants

# Temp file until I can figure out how to load
# data like this from a file in a way that also exports correctly

const male_names = ["Jacob",
"Michael",
"Joshua",
"Matthew",
"Daniel",
"Christopher",
"Andrew",
"Ethan",
"Joseph",
"William",
"Anthony",
"David",
"Alexander",
"Nicholas",
"Ryan",
"Tyler",
"James",
"John",
"Jonathan",
"Noah",
"Brandon",
"Christian",
"Dylan",
"Samuel",
"Benjamin",
"Nathan",
"Zachary",
"Logan",
"Justin",
"Gabriel",
"Jose",
"Austin",
"Kevin",
"Elijah",
"Caleb",
"Robert",
"Thomas",
"Jordan",
"Cameron",
"Jack",
"Hunter",
"Jackson",
"Angel",
"Isaiah",
"Evan",
"Isaac",
"Luke",
"Mason",
"Jayden",
"Jason",
"Gavin",
"Aaron",
"Connor",
"Aiden",
"Aidan",
"Kyle",
"Juan",
"Charles",
"Luis",
"Adam",
"Lucas",
"Brian",
"Eric",
"Adrian",
"Nathaniel",
"Sean",
"Alex",
"Carlos",
"Bryan",
"Ian",
"Owen",
"Jesus",
"Landon",
"Julian",
"Chase",
"Cole",
"Diego",
"Jeremiah",
"Steven",
"Sebastian",
"Xavier",
"Timothy",
"Carter",
"Wyatt",
"Brayden",
"Blake",
"Hayden",
"Devin",
"Cody",
"Richard",
"Seth",
"Dominic",
"Jaden",
"Antonio",
"Miguel",
"Liam",
"Patrick",
"Carson",
"Jesse",
"Tristan",
"Alejandro",
"Henry",
"Victor",
"Trevor",
"Bryce",
"Jake",
"Riley",
"Colin",
"Jared",
"Jeremy",
"Mark",
"Caden",
"Garrett",
"Parker",
"Marcus",
"Vincent",
"Kaleb",
"Kaden",
"Brady",
"Colton",
"Kenneth",
"Joel",
"Oscar",
"Josiah",
"Jorge",
"Ashton",
"Cooper",
"Tanner",
"Eduardo",
"Paul",
"Edward",
"Ivan",
"Preston",
"Maxwell",
"Alan",
"Levi",
"Stephen",
"Grant",
"Nicolas",
"Dakota",
"Omar",
"Alexis",
"George",
"Eli",
"Collin",
"Spencer",
"Gage",
"Max",
"Ricardo",
"Cristian",
"Derek",
"Micah",
"Brody",
"Francisco",
"Nolan",
"Ayden",
"Dalton",
"Shane",
"Peter",
"Damian",
"Jeffrey",
"Brendan",
"Travis",
"Fernando",
"Peyton",
"Conner",
"Andres",
"Javier",
"Giovanni",
"Shawn",
"Braden",
"Jonah",
"Bradley",
"Cesar",
"Emmanuel",
"Manuel",
"Edgar",
"Mario",
"Erik",
"Edwin",
"Johnathan",
"Devon",
"Erick",
"Wesley",
"Oliver",
"Trenton",
"Hector",
"Malachi",
"Jalen",
"Raymond",
"Gregory",
"Abraham",
"Elias",
"Leonardo",
"Sergio",
"Donovan",
"Colby",
"Marco",
"Bryson",
"Martin"]



const female_names = ["Emily",
"Madison",
"Emma",
"Olivia",
"Hannah",
"Abigail",
"Isabella",
"Samantha",
"Elizabeth",
"Ashley",
"Alexis",
"Sarah",
"Sophia",
"Alyssa",
"Grace",
"Ava",
"Taylor",
"Brianna",
"Lauren",
"Chloe",
"Natalie",
"Kayla",
"Jessica",
"Anna",
"Victoria",
"Mia",
"Hailey",
"Sydney",
"Jasmine",
"Julia",
"Morgan",
"Destiny",
"Rachel",
"Ella",
"Kaitlyn",
"Megan",
"Katherine",
"Savannah",
"Jennifer",
"Alexandra",
"Allison",
"Haley",
"Maria",
"Kaylee",
"Lily",
"Makayla",
"Brooke",
"Nicole",
"Mackenzie",
"Addison",
"Stephanie",
"Lillian",
"Andrea",
"Faith",
"Zoe",
"Kimberly",
"Madeline",
"Alexa",
"Katelyn",
"Gabriella",
"Gabrielle",
"Trinity",
"Amanda",
"Kylie",
"Mary",
"Paige",
"Riley",
"Leah",
"Jenna",
"Sara",
"Rebecca",
"Michelle",
"Sofia",
"Vanessa",
"Jordan",
"Angelina",
"Caroline",
"Avery",
"Audrey",
"Evelyn",
"Maya",
"Claire",
"Autumn",
"Jocelyn",
"Ariana",
"Nevaeh",
"Arianna",
"Jada",
"Bailey",
"Brooklyn",
"Aaliyah",
"Amber",
"Isabel",
"Mariah",
"Danielle",
"Melanie",
"Sierra",
"Erin",
"Amelia",
"Molly",
"Isabelle",
"Madelyn",
"Melissa",
"Jacqueline",
"Marissa",
"Angela",
"Shelby",
"Leslie",
"Katie",
"Jade",
"Catherine",
"Diana",
"Aubrey",
"Mya",
"Amy",
"Briana",
"Sophie",
"Gabriela",
"Breanna",
"Gianna",
"Kennedy",
"Gracie",
"Peyton",
"Adriana",
"Christina",
"Courtney",
"Daniela",
"Lydia",
"Kathryn",
"Valeria",
"Layla",
"Alexandria",
"Natalia",
"Angel",
"Laura",
"Charlotte",
"Margaret",
"Cheyenne",
"Miranda",
"Mikayla",
"Naomi",
"Kelsey",
"Payton",
"Ana",
"Alicia",
"Jillian",
"Daisy",
"Mckenzie",
"Ashlyn",
"Sabrina",
"Caitlin",
"Summer",
"Ruby",
"Valerie",
"Rylee",
"Skylar",
"Lindsey",
"Kelly",
"Genesis",
"Zoey",
"Eva",
"Sadie",
"Alexia",
"Cassidy",
"Kylee",
"Kendall",
"Jordyn",
"Kate",
"Jayla",
"Karen",
"Tiffany",
"Cassandra",
"Juliana",
"Reagan",
"Caitlyn",
"Giselle",
"Serenity",
"Alondra",
"Lucy",
"Bianca",
"Kiara",
"Crystal",
"Erica",
"Angelica",
"Hope",
"Chelsea",
"Alana",
"Liliana",
"Brittany",
"Camila",
"Makenzie",
"Lilly",
"Veronica",
"Abby",
"Jazmin",
"Adrianna",
"Delaney",
"Karina",
"Ellie",
"Jasmin"]

const num_male_faces = 264
const num_female_faces = 425

# These are some bios I found here: https://inspirationfeed.com/humble-quotes/
# They're kind of all over the place but should be a good placeholder for now.
const bios = [
	"A lie is just a great story ruined by truth.",
	"Actually, I’m not funny, I’m having a mental disorder",
	"Chaos, panic & disorder – my work here is done.",
	"Did my opinion offend you? You should hear the ones I don’t say out loud.",
	"Don’t worry if plan A fails; there are twenty-five other letters in the alphabet.",
	"Eat right. Stay in shape. Die anyway.",
	"Gifted napper, talker, and ice cream eater.",
	"I always learn from mistake of others who take my advice.",
	"I apologize for anything I say while hungry",
	"I might look like I’m doing nothing, but in my head, I’m quite busy.",
	"I only drink on two occasions: when it’s my birthday and when it’s not.",
	"I prefer my puns intended.",
	"I talk like a baby and I never pay for drinks.",
	"I thought I wanted a career, turns out I just wanted paychecks.",
	"I wanted to lose 10 pounds this year. Only 13 to go.",
	"I’m in desperate need of a 6 month vacation… Twice a year.",
	"I’m not lazy, I’m on energy-saving mode.",
	"I’m not smart. I just wear glasses.",
	"I’m not sure how many problems I have because math is one of them.",
	"It takes patience to listen... it takes skill to pretend you’re listening.",
	"Living proof that pobody’s nerfect.",
	"Money talks; all mine say is ‘goodbye’",
	"One day, I hope to become a grown up",
	"Recommended by 4 out of 5 people that recommend things.",
	"Recovering ice cream addict",
	"Sassy, classy with a touch of badassy",
	"Some people are alive only because it’s illegal to kill them.",
	"The last thing I want to do is hurt you. But it’s still on the list.",
	"The older I get, the more everyone can kiss my ass.",
	"The only reason I am fat is because a tiny body couldn’t store all this personality.",
	"The problem is, you think you’re smart",
	"The truth will set you free, but first it will piss you off.",
	"Used to think I was a tad indecisive, but now I’m not quite sure",
	"What if there were no hypothetical questions?",
	"Where the hell am I, and how did I get here?",
	"Why don’t some couples go to the gym? Because some relationships don’t work out.",
	"Words cannot express my passion and love for Fridays",
	"You do realize makeup isn’t going to fix your stupidity?"
]
